- hosts: all
  become_user: root

  roles:
    - { role: apt, tags: 'apt' }
    - { role: docker.io, tags: 'docker.io' }
    - { role: kubernetes, tags: 'kubernetes'}
    - { role: swapoff, tags: 'swapoff'}

- hosts: master
  become_user: root

  roles:
   - { role: snap, tags: 'snap'}
   - { role: create-cluster, tags: 'create-cluster'}
   - { role: metallb, tags: 'metallb'}
   - { role: nginx-ingress, tags: 'nginx-ingress'}
   - { role: longhorn, tags: 'longhorn'}

- hosts: workers
  become_user: root

  roles:
   - { role: join-cluster, tags: 'join-cluster'}


- hosts: master
  become_user: root

  roles:
   - { role: argocd, tags: 'argocd'}