---
- name: Update cache
  become: true
  apt:
    update_cache: yes
  when: apt.update

- name: Upgrade packages to latest
  become: true
  apt:
    upgrade: dist
  when: apt.upgrade

- name: apt install python3-pip
  become: true
  apt:
    name: python3-pip
    state: latest