---
- name: Copy join command from Ansiblehost to the worker nodes.
  become: true
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes to the cluster.
  become: true
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not