---
- name: Copy argocd-value.yaml
  become: true
  copy:
    src: roles/argocd/files/argocd-value.yaml
    dest: /tmp/argocd-value.yaml
    mode: 0777
- name: Helm Repo add argocd
  kubernetes.core.helm_repository:
    name: argocd
    url: https://argoproj.github.io/argo-helm
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present
- name: Apply argocd ingress
  become: true
  ansible.builtin.replace:
    path: /tmp/argocd-value.yaml
    regexp: argocd.example.com
    replace: argocd.{{ingress.host}}
- name: Deploy argo-cd helm chart
  block:
    - name: helm upgrade argocd
      become_user: root
      shell: helm upgrade argocd argocd/argo-cd --version v5.8.3 --namespace argocd --values /tmp/argocd-value.yaml
  rescue:
    - name: helm deploy argocd
      become_user: root
      shell: helm install argocd argocd/argo-cd --version v5.8.3 --namespace argocd --values /tmp/argocd-value.yaml