- name: Copy nginx-ingress.yaml
  become: true
  copy:
    src: roles/nginx-ingress/files/nginx-ingress.yaml
    dest: /tmp/nginx-ingress.yaml
    mode: 0777
  
- name: Deploy nginx ingress controller
  kubernetes.core.k8s:
    state: present
    src: /tmp/nginx-ingress.yaml